require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# DSL & test convenience exceptions

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - require
    - require_relative
    - puts
    - raise
    - rescue_from
    - render
    - head
    - redirect_to
    - send_data
    - mail
    - desc
    - info
    - warn
    - error
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - '**/*.jbuilder'
    - 'Gemfile'
    - 'config.ru'

Style/RescueModifier:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  ExcludedMethods:
    - 'feature'
    - 'describe'
    - 'context'
    - 'scenario'
    - 'draw'
    - 'configure'
    - 'namespace'
    - 'shared_examples'
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Max: 15
  Exclude:
    - 'spec/features/**/*'

# Customized cops

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/MethodLength:
  Max: 15
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Capybara/FeatureMethods:
  EnabledMethods:
    - 'feature'
    - 'scenario'
    - 'xscenario'

# Disabled cops

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

# Pending for 1.0--revisit when upgrading
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringConcatenation:
  Enabled: true
