 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/climate_action_categories", type: :request do
  
  # ClimateActionCategory. As you add validations to ClimateActionCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ClimateActionCategory.create! valid_attributes
      get climate_action_categories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      climate_action_category = ClimateActionCategory.create! valid_attributes
      get climate_action_category_url(climate_action_category)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_climate_action_category_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      climate_action_category = ClimateActionCategory.create! valid_attributes
      get edit_climate_action_category_url(climate_action_category)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ClimateActionCategory" do
        expect {
          post climate_action_categories_url, params: { climate_action_category: valid_attributes }
        }.to change(ClimateActionCategory, :count).by(1)
      end

      it "redirects to the created climate_action_category" do
        post climate_action_categories_url, params: { climate_action_category: valid_attributes }
        expect(response).to redirect_to(climate_action_category_url(ClimateActionCategory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ClimateActionCategory" do
        expect {
          post climate_action_categories_url, params: { climate_action_category: invalid_attributes }
        }.to change(ClimateActionCategory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post climate_action_categories_url, params: { climate_action_category: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested climate_action_category" do
        climate_action_category = ClimateActionCategory.create! valid_attributes
        patch climate_action_category_url(climate_action_category), params: { climate_action_category: new_attributes }
        climate_action_category.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the climate_action_category" do
        climate_action_category = ClimateActionCategory.create! valid_attributes
        patch climate_action_category_url(climate_action_category), params: { climate_action_category: new_attributes }
        climate_action_category.reload
        expect(response).to redirect_to(climate_action_category_url(climate_action_category))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        climate_action_category = ClimateActionCategory.create! valid_attributes
        patch climate_action_category_url(climate_action_category), params: { climate_action_category: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested climate_action_category" do
      climate_action_category = ClimateActionCategory.create! valid_attributes
      expect {
        delete climate_action_category_url(climate_action_category)
      }.to change(ClimateActionCategory, :count).by(-1)
    end

    it "redirects to the climate_action_categories list" do
      climate_action_category = ClimateActionCategory.create! valid_attributes
      delete climate_action_category_url(climate_action_category)
      expect(response).to redirect_to(climate_action_categories_url)
    end
  end
end
